package com.minimall.common.core.audit;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.minimall.common.core.exception.BusinessException;
import com.minimall.common.core.exception.ErrorCode;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class JdbcAdminAuditWriterTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    @Test
    void writesAuditLogToDatabase() throws Exception {
        JdbcTemplate jdbcTemplate = jdbcTemplateWithAuditTable();
        JdbcAdminAuditWriter writer = new JdbcAdminAuditWriter(jdbcTemplate);

        writer.write(new AdminAuditLogWriteRequest(
                1001L,
                "admin",
                AdminAuditAction.INVENTORY_ADJUST,
                AdminAuditResourceType.INVENTORY,
                "SKU-1",
                "REQ-1",
                AdminAuditSourceType.AI_SUGGESTION,
                "AIS-1",
                objectMapper.readTree("{\"availableStock\":8}"),
                objectMapper.readTree("{\"availableStock\":13}"),
                "127.0.0.1",
                "Mozilla/5.0",
                "Adjust SKU-1 stock by 5"));

        Map<String, Object> row = jdbcTemplate.queryForMap(
                "SELECT * FROM admin_operation_logs WHERE request_id = ?",
                "REQ-1");
        assertThat(row.get("ADMIN_USER_ID")).isEqualTo(1001L);
        assertThat(row.get("ADMIN_USERNAME")).isEqualTo("admin");
        assertThat(row.get("ACTION")).isEqualTo("INVENTORY_ADJUST");
        assertThat(row.get("RESOURCE_TYPE")).isEqualTo("INVENTORY");
        assertThat(row.get("RESOURCE_ID")).isEqualTo("SKU-1");
        assertThat(row.get("SOURCE_TYPE")).isEqualTo("AI_SUGGESTION");
        assertThat(row.get("REFERENCE_NO")).isEqualTo("AIS-1");
        assertThat(row.get("BEFORE_SNAPSHOT").toString()).contains("\"availableStock\":8");
        assertThat(row.get("AFTER_SNAPSHOT").toString()).contains("\"availableStock\":13");
        assertThat(row.get("IP")).isEqualTo("127.0.0.1");
        assertThat(row.get("USER_AGENT")).isEqualTo("Mozilla/5.0");
        assertThat(row.get("SUMMARY")).isEqualTo("Adjust SKU-1 stock by 5");
        assertThat(row.get("CREATED_AT")).isNotNull();
    }

    @Test
    void writesDefaultManualSourceFromRequestContract() {
        JdbcTemplate jdbcTemplate = jdbcTemplateWithAuditTable();
        JdbcAdminAuditWriter writer = new JdbcAdminAuditWriter(jdbcTemplate);

        writer.write(new AdminAuditLogWriteRequest(
                1001L,
                "admin",
                AdminAuditAction.PRODUCT_CREATE,
                AdminAuditResourceType.PRODUCT,
                "SKU-1",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                "Create SKU-1"));

        assertThat(jdbcTemplate.queryForObject(
                "SELECT source_type FROM admin_operation_logs WHERE resource_id = ?",
                String.class,
                "SKU-1"))
                .isEqualTo("ADMIN_MANUAL");
    }

    @Test
    void wrapsDatabaseFailureAsBusinessException() {
        JdbcTemplate jdbcTemplate = new JdbcTemplate(newDataSource());
        JdbcAdminAuditWriter writer = new JdbcAdminAuditWriter(jdbcTemplate);

        assertThatThrownBy(() -> writer.write(new AdminAuditLogWriteRequest(
                1001L,
                "admin",
                AdminAuditAction.PRODUCT_CREATE,
                AdminAuditResourceType.PRODUCT,
                "SKU-1",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                "Create SKU-1")))
                .isInstanceOf(BusinessException.class)
                .extracting("errorCode")
                .isEqualTo(ErrorCode.INTERNAL_ERROR);
    }

    private JdbcTemplate jdbcTemplateWithAuditTable() {
        JdbcTemplate jdbcTemplate = new JdbcTemplate(newDataSource());
        jdbcTemplate.execute("""
                CREATE TABLE admin_operation_logs (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  admin_user_id BIGINT NOT NULL,
                  admin_username VARCHAR(64) NOT NULL,
                  action VARCHAR(64) NOT NULL,
                  resource_type VARCHAR(64) NOT NULL,
                  resource_id VARCHAR(128),
                  request_id VARCHAR(128),
                  source_type VARCHAR(64) NOT NULL DEFAULT 'ADMIN_MANUAL',
                  reference_no VARCHAR(128),
                  before_snapshot VARCHAR(8192),
                  after_snapshot VARCHAR(8192),
                  ip VARCHAR(64),
                  user_agent VARCHAR(512),
                  summary VARCHAR(512) NOT NULL,
                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        return jdbcTemplate;
    }

    private DriverManagerDataSource newDataSource() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:admin_audit_writer_" + System.nanoTime() + ";DB_CLOSE_DELAY=-1");
        dataSource.setUsername("sa");
        dataSource.setPassword("");
        return dataSource;
    }
}
