package com.minimall.common.core.audit;

public enum AdminAuditAction {
    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_ON_SHELF,
    PRODUCT_OFF_SHELF,
    INVENTORY_INITIALIZE,
    INVENTORY_ADJUST,
    INBOUND_ORDER_CREATE,
    INBOUND_ORDER_CONFIRM,
    AI_SUGGESTION_CREATE,
    AI_SUGGESTION_APPLY,
    AI_SUGGESTION_REJECT
}
