CREATE TABLE IF NOT EXISTS ai_operation_suggestion (
  id BIGINT NOT NULL AUTO_INCREMENT,
  suggestion_no VARCHAR(64) NOT NULL,
  type VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW',
  source VARCHAR(64) NOT NULL,
  reason VARCHAR(1024) NULL,
  input_snapshot_ref VARCHAR(128) NULL,
  input_summary TEXT NULL,
  linked_inbound_no VARCHAR(64) NULL,
  rejected_reason VARCHAR(512) NULL,
  reviewed_by_admin_user_id BIGINT NULL,
  reviewed_by_admin_username VARCHAR(64) NULL,
  reviewed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_ai_operation_suggestion_no (suggestion_no),
  KEY idx_ai_operation_suggestion_status_created (status, created_at),
  KEY idx_ai_operation_suggestion_type_created (type, created_at),
  KEY idx_ai_operation_suggestion_linked_inbound_no (linked_inbound_no),
  KEY idx_ai_operation_suggestion_reviewed_at (reviewed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_operation_suggestion_item (
  id BIGINT NOT NULL AUTO_INCREMENT,
  suggestion_no VARCHAR(64) NOT NULL,
  product_id VARCHAR(64) NOT NULL,
  product_name VARCHAR(128) NULL,
  available_stock INT NULL,
  locked_stock INT NULL,
  safety_stock INT NULL,
  sold_quantity_last_7_days INT NULL,
  suggested_quantity INT NOT NULL,
  risk_level VARCHAR(32) NOT NULL DEFAULT 'MEDIUM',
  reason VARCHAR(1024) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_ai_operation_suggestion_item_product (suggestion_no, product_id),
  KEY idx_ai_operation_suggestion_item_suggestion_no (suggestion_no),
  KEY idx_ai_operation_suggestion_item_product_id (product_id),
  CONSTRAINT fk_ai_operation_suggestion_item_suggestion_no
    FOREIGN KEY (suggestion_no) REFERENCES ai_operation_suggestion (suggestion_no),
  CONSTRAINT chk_ai_operation_suggestion_item_suggested_positive CHECK (suggested_quantity > 0),
  CONSTRAINT chk_ai_operation_suggestion_item_available_non_negative CHECK (available_stock IS NULL OR available_stock >= 0),
  CONSTRAINT chk_ai_operation_suggestion_item_locked_non_negative CHECK (locked_stock IS NULL OR locked_stock >= 0),
  CONSTRAINT chk_ai_operation_suggestion_item_safety_non_negative CHECK (safety_stock IS NULL OR safety_stock >= 0),
  CONSTRAINT chk_ai_operation_suggestion_item_sold7_non_negative CHECK (sold_quantity_last_7_days IS NULL OR sold_quantity_last_7_days >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
