CREATE TABLE IF NOT EXISTS admin_operation_logs (
  id BIGINT NOT NULL AUTO_INCREMENT,
  admin_user_id BIGINT NOT NULL,
  admin_username VARCHAR(64) NOT NULL,
  action VARCHAR(64) NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_id VARCHAR(128) NULL,
  request_id VARCHAR(128) NULL,
  source_type VARCHAR(64) NOT NULL DEFAULT 'ADMIN_MANUAL',
  reference_no VARCHAR(128) NULL,
  before_snapshot JSON NULL,
  after_snapshot JSON NULL,
  ip VARCHAR(64) NULL,
  user_agent VARCHAR(512) NULL,
  summary VARCHAR(512) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_admin_operation_logs_admin_created (admin_user_id, created_at),
  KEY idx_admin_operation_logs_action_created (action, created_at),
  KEY idx_admin_operation_logs_resource (resource_type, resource_id),
  KEY idx_admin_operation_logs_request_id (request_id),
  KEY idx_admin_operation_logs_source_ref (source_type, reference_no),
  KEY idx_admin_operation_logs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
