spring:
  application:
    name: product-service

server:
  port: 8102

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
