apiVersion: 1

datasources:
  - name: Prometheus
    uid: minimall-prometheus
    type: prometheus
    access: proxy
    url: ${GRAFANA_PROMETHEUS_URL}
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
